# Generated by Django 5.0 on 2024-01-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profilepicture_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
