# Generated by Django 5.0 on 2024-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendent',
            field=models.IntegerField(default=0),
        ),
    ]
