# Generated by Django 5.0 on 2024-01-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0008_upcomingevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
    ]
