# Generated by Django 5.0 on 2024-01-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_remove_event_categories_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
