# Generated by Django 5.0 on 2024-01-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('organizers', '0007_event_attendent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendent')),
            ],
        ),
    ]
