# Generated by Django 5.0 on 2024-01-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_event_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_accept',
            old_name='user',
            new_name='name',
        ),
    ]
