# Generated by Django 5.0 on 2024-01-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_rename_user_event_accept_name'),
        ('organizers', '0011_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(to='organizers.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendent')),
            ],
        ),
    ]
